/*
 * Reads the source workbook and regenerates:
 *   supabase/migrations/0002_workbook.sql   — one table per sheet, every column, RLS open
 *   js/workbook_schema.js                    — window.WORKBOOK_SCHEMA used by the importer
 *
 * Table + label names are derived from sheet names only — any leading bank word
 * (see BANK_WORDS) is stripped so nothing is issuer-specific.
 *
 * Re-run whenever the workbook's sheets or headers change:
 *   npm i --no-save xlsx@0.18.5 && node scripts/gen_workbook_schema.js [path/to/workbook.xlsx]
 */
const fs = require('fs');
const path = require('path');
const XLSX = require('xlsx');

const ROOT = path.join(__dirname, '..');
const WB = process.argv[2] || path.join(ROOT, 'HDFC_Credit_Cards_final.xlsx');

// Leading issuer words to drop from sheet names so table names stay generic.
const BANK_WORDS = ['hdfc', 'icici', 'sbi', 'axis', 'kotak', 'yes', 'idfc', 'rbl', 'amex', 'american express', 'citi', 'hsbc', 'standard chartered', 'indusind', 'au', 'bob', 'bank of baroda', 'pnb'];
const stripBank = (name) => {
    let s = String(name).trim();
    for (const w of BANK_WORDS) {
        const re = new RegExp('^' + w.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + '\\b[\\s_-]*', 'i');
        if (re.test(s)) { s = s.replace(re, ''); break; }
    }
    return s.trim() || String(name).trim();
};

const snake = (s) => String(s)
    .replace(/%/g, ' pct ')
    .replace(/[₹$]/g, ' inr ')
    .replace(/&/g, ' and ')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .replace(/_+/g, '_') || 'col';

// wb_ prefix keeps these clear of the per-page import tables in 0001 (cards, offers, mcc_rules).
// Bank word stripped first so "HDFC Card Details" -> wb_card_details.
const tableName = (sheet) => 'wb_' + snake(stripBank(sheet)).replace(/^(\d)/, '_$1');

// Dedupe repeated / colliding column names within one sheet: foo, foo_2, foo_3 ...
function dedupe(names) {
    const seen = {};
    return names.map((n) => {
        let base = snake(n);
        if (/^\d/.test(base)) base = 'c_' + base;
        seen[base] = (seen[base] || 0) + 1;
        return seen[base] === 1 ? base : `${base}_${seen[base]}`;
    });
}

// Sheets to ignore entirely (matched on bank-stripped, case-insensitive name).
const SKIP_SHEETS = ['audit log'];

const wb = XLSX.readFile(WB);
const schema = {};
const sqlParts = [
    '-- GENERATED by scripts/gen_workbook_schema.js — do not edit by hand.',
    '-- One table per sheet of the source workbook. Every column is text.',
    '-- Re-run the generator to update.',
    ''
];

wb.SheetNames.forEach((sheet) => {
    if (SKIP_SHEETS.includes(stripBank(sheet).toLowerCase())) return;
    const rows = XLSX.utils.sheet_to_json(wb.Sheets[sheet], { header: 1, defval: '' });
    const rawHeader = (rows[0] || []).map((h) => String(h).trim()).filter((h) => h !== '');
    if (rawHeader.length === 0) return;

    const cols = dedupe(rawHeader);
    const table = tableName(sheet);

    // which column carries the card id (for indexing)
    const cardIdCol = cols[rawHeader.findIndex((h) => /^card ?id$/i.test(h))] || null;

    // `cols` is positional: column i in the sheet's header row -> cols[i].
    // The importer maps by position, so duplicate headers (Lounge Int/Dom blocks)
    // are all preserved. Re-run the generator if a sheet's columns are reordered.
    // key = real sheet name (needed to find the sheet in the uploaded file);
    // label = bank-stripped, shown on the Extract Benefits checkboxes.
    schema[sheet] = { table, label: stripBank(sheet), cardIdCol, cols };

    sqlParts.push(`-- ${schema[sheet].label}  (${rows.length - 1} data rows)`);
    sqlParts.push(`drop table if exists ${table} cascade;`);
    sqlParts.push(`create table ${table} (`);
    sqlParts.push(`    id uuid primary key default gen_random_uuid(),`);
    sqlParts.push(cols.map((c) => `    ${c} text`).join(',\n') + ',');
    sqlParts.push(`    imported_at timestamptz default now()`);
    sqlParts.push(`);`);
    if (cardIdCol) sqlParts.push(`create index ${table}_card_idx on ${table} (${cardIdCol});`);
    sqlParts.push('');
});

// RLS: open policy for anon + authenticated on every generated table.
sqlParts.push('do $$');
sqlParts.push('declare t text;');
sqlParts.push('begin');
sqlParts.push(`    foreach t in array array[${Object.values(schema).map((s) => `'${s.table}'`).join(', ')}]`);
sqlParts.push('    loop');
sqlParts.push("        execute format('alter table %I enable row level security', t);");
sqlParts.push("        execute format('drop policy if exists %I_anon_all on %I', t, t);");
sqlParts.push("        execute format('create policy %I_anon_all on %I for all to anon, authenticated using (true) with check (true)', t, t);");
sqlParts.push('    end loop;');
sqlParts.push('end $$;');
sqlParts.push('');

fs.writeFileSync(path.join(ROOT, 'supabase/migrations/0002_workbook.sql'), sqlParts.join('\n'));
fs.writeFileSync(
    path.join(ROOT, 'js/workbook_schema.js'),
    '// GENERATED by scripts/gen_workbook_schema.js — do not edit by hand.\n' +
    'window.WORKBOOK_SCHEMA = ' + JSON.stringify(schema, null, 2) + ';\n'
);

console.log('sheets mapped:', Object.keys(schema).length);
Object.entries(schema).forEach(([s, v]) =>
    console.log(`  ${s}  ->  ${v.table}  (${v.cols.length} cols, card id: ${v.cardIdCol || '—'})`)
);
