-- GENERATED by scripts/gen_workbook_schema.js — do not edit by hand.
-- One table per sheet of the source workbook. Every column is text.
-- Re-run the generator to update.

-- Card Details  (999 data rows)
drop table if exists wb_card_details cascade;
create table wb_card_details (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    instrument_type text,
    issuer text,
    product text,
    network text,
    subnetwork text,
    issuercountry text,
    cardstatus text,
    cardstatusdate text,
    cardweblink text,
    cardaltlink text,
    card_spend_per_point text,
    card_rp_conversion text,
    apr text,
    card_bill_cycle_duration text,
    card_bill_date text,
    cobrand text,
    rewardprogram text,
    agemin text,
    agemax text,
    creditscore text,
    emptype text,
    salary text,
    producttype text,
    nationality text,
    fee_joining_type text,
    fee_joining text,
    fee_annual text,
    fee_renewal text,
    fee_waiver_spend text,
    fee_waiver_period text,
    benefit_concierge text,
    benefit_dining text,
    benefit_golf text,
    benefit_movie text,
    benefit_spa text,
    benefit_insurance text,
    benefit_fees text,
    benefit_contactless text,
    benefit_tokenenabled text,
    benefit_upisupported text,
    benefit_welcome text,
    benefit_feewaiver text,
    benefit_fuel text,
    benefit_lounge text,
    benefit_milestone text,
    benefit_partnerprogram text,
    benefit_airporttransfer text,
    benefit_travel text,
    benefit_hotel text,
    benefit_airline text,
    benefit_forex text,
    benefit_rewardpoints text,
    benefit_renewalbenefit text,
    benefit_shopping text,
    benefit_ott text,
    benefit_travelinsurance text,
    benefit_purchaseprotection text,
    benefit_personalaccident text,
    benefit_roadsideassistance text,
    benefit_ltf text,
    benefit_statusbenefits text,
    imported_at timestamptz default now()
);
create index wb_card_details_card_idx on wb_card_details (cardid);

-- Offers  (2288 data rows)
drop table if exists wb_offers cascade;
create table wb_offers (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    offerid text,
    category text,
    subcategory text,
    rewardtype text,
    frequency text,
    status text,
    days text,
    instanceperiod text,
    person text,
    mintx text,
    maxtx text,
    maxbenefit text,
    rewardcap text,
    startdate text,
    enddate text,
    weblink text,
    paymentscopetype text,
    paymentscopevalue text,
    rpexpiry text,
    couponcode text,
    platform text,
    customplatform text,
    rp_pointtype text,
    rp_calc text,
    cb_type text,
    cb_credit text,
    cb_limit text,
    cb_freq text,
    id_partner text,
    id_discount text,
    id_paymode text,
    id_max text,
    vd_slab text,
    vd_pct text,
    vd_max text,
    v_brand text,
    v_type text,
    v_value text,
    v_delivery text,
    am_airline text,
    am_program text,
    am_ratio text,
    am_time text,
    hp_chain text,
    hp_program text,
    hp_ratio text,
    hp_time text,
    c_program text,
    c_type text,
    c_conv text,
    c_validity text,
    imported_at timestamptz default now()
);
create index wb_offers_card_idx on wb_offers (cardid);

-- Lounge  (999 data rows)
drop table if exists wb_lounge cascade;
create table wb_lounge (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    lounge_usage_type text,
    lounge_type text,
    access_type text,
    domestic_international text,
    visits_per_period text,
    lounge_program text,
    eligible_airports text,
    eligible_terminals text,
    network_requirement text,
    boarding_pass_required text,
    cardholder_guest_rule text,
    guest_fee text,
    additional_visit_fee text,
    spend_threshold text,
    spend_lookback_period text,
    imported_at timestamptz default now()
);
create index wb_lounge_card_idx on wb_lounge (cardid);

-- Airport Transfer  (999 data rows)
drop table if exists wb_airport_transfer cascade;
create table wb_airport_transfer (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    transfer_provider text,
    transfer_type text,
    free_transfers text,
    transfer_frequency text,
    meet_and_greet text,
    meet_and_greet_count text,
    meet_and_greet_frequency text,
    eligible_airports text,
    eligible_cities text,
    minimum_spend text,
    booking_channel text,
    advance_booking text,
    guest_policy text,
    imported_at timestamptz default now()
);
create index wb_airport_transfer_card_idx on wb_airport_transfer (cardid);

-- Travel  (999 data rows)
drop table if exists wb_travel cascade;
create table wb_travel (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    travel_provider text,
    booking_channel text,
    travel_discount text,
    travel_reward_rate text,
    minimum_booking_value text,
    maximum_discount text,
    eligible_products text,
    blackout_period text,
    coupon_code text,
    travel_portal text,
    imported_at timestamptz default now()
);
create index wb_travel_card_idx on wb_travel (cardid);

-- Hotel  (999 data rows)
drop table if exists wb_hotel cascade;
create table wb_hotel (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    hotel_sub_benefits text,
    hotel_partner text,
    hotel_program text,
    discount_percent text,
    room_upgrade text,
    complimentary_night text,
    breakfast_included text,
    early_checkin text,
    late_checkout text,
    status_match text,
    eligible_properties text,
    blackout_dates text,
    imported_at timestamptz default now()
);
create index wb_hotel_card_idx on wb_hotel (cardid);

-- Airline  (999 data rows)
drop table if exists wb_airline cascade;
create table wb_airline (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    airline_partner text,
    airline_program text,
    discount_percent text,
    miles_bonus text,
    status_benefit text,
    upgrade_benefit text,
    eligible_routes text,
    booking_channel text,
    minimum_fare text,
    maximum_discount text,
    imported_at timestamptz default now()
);
create index wb_airline_card_idx on wb_airline (cardid);

-- Forex - International  (999 data rows)
drop table if exists wb_forex_international cascade;
create table wb_forex_international (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    forex_ccy_markup text,
    conversion_charge text,
    imported_at timestamptz default now()
);
create index wb_forex_international_card_idx on wb_forex_international (cardid);

-- Reward Points  (999 data rows)
drop table if exists wb_reward_points cascade;
create table wb_reward_points (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    reward_rule_id text,
    earn_category text,
    merchant text,
    expense_mode text,
    points_per_rupee text,
    multiplier text,
    base_reward_rate text,
    accelerated_reward_rate text,
    minimum_transaction text,
    monthly_cap_points text,
    monthly_cap_spend text,
    annual_cap_points text,
    excluded_mccs text,
    excluded_transaction_types text,
    imported_at timestamptz default now()
);
create index wb_reward_points_card_idx on wb_reward_points (cardid);

-- Milestone  (999 data rows)
drop table if exists wb_milestone cascade;
create table wb_milestone (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    milestone_id text,
    milestone_period text,
    milestone_tier text,
    spend_from text,
    spend_to text,
    milestone_benefit_type text,
    milestone_benefit_value text,
    cumulative_or_incremental text,
    milestone_reset text,
    milestone_achievement_date text,
    benefit_issuance_method text,
    stacking_rule text,
    imported_at timestamptz default now()
);
create index wb_milestone_card_idx on wb_milestone (cardid);

-- Welcome  (999 data rows)
drop table if exists wb_welcome cascade;
create table wb_welcome (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    welcome_benefit_id text,
    welcome_benefit_type text,
    welcome_benefit_component text,
    welcome_value text,
    joining_fee_linkage text,
    minimum_spend text,
    spend_period text,
    activation_required text,
    activation_deadline text,
    benefit_delivery_method text,
    redemption_portal text,
    delivery_timeline text,
    expiry_date text,
    component_realistic_value text,
    imported_at timestamptz default now()
);
create index wb_welcome_card_idx on wb_welcome (cardid);

-- Renewal Benefit  (999 data rows)
drop table if exists wb_renewal_benefit cascade;
create table wb_renewal_benefit (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    renewal_benefit_id text,
    renewal_benefit_type text,
    renewal_benefit_component text,
    renewal_value text,
    renewal_fee_linkage text,
    minimum_spend_for_renewal_benefit text,
    qualifying_period text,
    activation_required text,
    benefit_delivery_method text,
    redemption_portal text,
    delivery_timeline text,
    expiry_date text,
    realistic_value text,
    imported_at timestamptz default now()
);
create index wb_renewal_benefit_card_idx on wb_renewal_benefit (cardid);

-- Fee Waiver  (999 data rows)
drop table if exists wb_fee_waiver cascade;
create table wb_fee_waiver (
    id uuid primary key default gen_random_uuid(),
    card_id text,
    fee_type text,
    fee_amount text,
    waiver_amount text,
    waiver_threshold text,
    waiver_period text,
    qualifying_spend_definition text,
    exclusions text,
    automatic_waiver text,
    waiver_qualification_date text,
    partial_waiver_allowed text,
    imported_at timestamptz default now()
);
create index wb_fee_waiver_card_idx on wb_fee_waiver (card_id);

-- Partner & Transfer  (999 data rows)
drop table if exists wb_partner_and_transfer cascade;
create table wb_partner_and_transfer (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    redemption_mode text,
    partner_name text,
    conversion_ratio text,
    minimum_transfer text,
    transfer_increment text,
    transfer_fee text,
    transfer_time text,
    notes text,
    imported_at timestamptz default now()
);
create index wb_partner_and_transfer_card_idx on wb_partner_and_transfer (cardid);

-- Fuel  (999 data rows)
drop table if exists wb_fuel cascade;
create table wb_fuel (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    fuel_waiver_period text,
    fuel_max_tx_count text,
    fuel_count_period text,
    fuel_surcharge_rate text,
    waiver_rate text,
    waiver_type text,
    minimum_fuel_transaction text,
    maximum_fuel_transaction text,
    monthly_waiver_cap text,
    annual_waiver_cap text,
    eligible_fuel_stations text,
    eligible_mccs text,
    gst_reversal text,
    gst_reversal_rate text,
    fuel_reward_rate text,
    net_effective_fuel_benefit text,
    imported_at timestamptz default now()
);
create index wb_fuel_card_idx on wb_fuel (cardid);

-- Dining  (999 data rows)
drop table if exists wb_dining cascade;
create table wb_dining (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    dining_platform text,
    dining_discount_value text,
    dining_restaurant_mapping text,
    dining_program text,
    restaurant_name text,
    restaurant_id text,
    discount_percent text,
    cashback_percent text,
    minimum_bill text,
    maximum_discount text,
    eligible_days text,
    meal_type text,
    booking_platform text,
    reservation_required text,
    delivery_app text,
    dine_in_only text,
    tip_excluded text,
    tax_excluded text,
    imported_at timestamptz default now()
);
create index wb_dining_card_idx on wb_dining (cardid);

-- Golf  (999 data rows)
drop table if exists wb_golf cascade;
create table wb_golf (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    golf_benefit_type text,
    free_rounds text,
    round_frequency text,
    golf_course text,
    golf_course_network text,
    lesson_available text,
    lesson_count text,
    caddie_included text,
    guest_allowed text,
    booking_window text,
    handicap_requirement text,
    additional_round_fee text,
    imported_at timestamptz default now()
);
create index wb_golf_card_idx on wb_golf (cardid);

-- Movie  (999 data rows)
drop table if exists wb_movie cascade;
create table wb_movie (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    movie_platform text,
    ticket_benefit_type text,
    free_tickets text,
    discount_percent text,
    ticket_cap text,
    monthly_ticket_limit text,
    monthly_benefit_cap text,
    booking_fee text,
    eligible_days text,
    eligible_cinemas text,
    minimum_spend text,
    imported_at timestamptz default now()
);
create index wb_movie_card_idx on wb_movie (cardid);

-- SPA - Wellness  (999 data rows)
drop table if exists wb_spa_wellness cascade;
create table wb_spa_wellness (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    spa_provider text,
    spa_location text,
    service_type text,
    free_sessions text,
    session_value text,
    frequency text,
    discount_percent text,
    minimum_spend text,
    booking_required text,
    eligible_properties text,
    guest_policy text,
    imported_at timestamptz default now()
);
create index wb_spa_wellness_card_idx on wb_spa_wellness (cardid);

-- Concierge  (999 data rows)
drop table if exists wb_concierge cascade;
create table wb_concierge (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    concierge_provider text,
    service_categories text,
    availability text,
    operating_hours text,
    booking_channel text,
    international_support text,
    premium_services text,
    service_fee text,
    imported_at timestamptz default now()
);
create index wb_concierge_card_idx on wb_concierge (cardid);

-- Shopping  (999 data rows)
drop table if exists wb_shopping cascade;
create table wb_shopping (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    merchant text,
    merchant_category text,
    discount_percent text,
    cashback_percent text,
    minimum_transaction text,
    maximum_discount text,
    coupon_code text,
    campaign_frequency text,
    online_offline text,
    stacking_rule text,
    imported_at timestamptz default now()
);
create index wb_shopping_card_idx on wb_shopping (cardid);

-- OTT - Subscription  (999 data rows)
drop table if exists wb_ott_subscription cascade;
create table wb_ott_subscription (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    platform text,
    subscription_type text,
    subscription_duration text,
    subscription_value text,
    monthly_value text,
    annual_value text,
    activation_method text,
    renewal_rule text,
    minimum_spend text,
    imported_at timestamptz default now()
);
create index wb_ott_subscription_card_idx on wb_ott_subscription (cardid);

-- Insurance - Protection  (999 data rows)
drop table if exists wb_insurance_protection cascade;
create table wb_insurance_protection (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    policy_type text,
    insurer text,
    coverage_amount text,
    activation_trigger text,
    minimum_spend text,
    deductible text,
    covered_items text,
    exclusions text,
    claim_process text,
    claim_sla text,
    imported_at timestamptz default now()
);
create index wb_insurance_protection_card_idx on wb_insurance_protection (cardid);

-- Travel Insurance  (999 data rows)
drop table if exists wb_travel_insurance cascade;
create table wb_travel_insurance (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    policy_type text,
    insurer text,
    policy_number_reference text,
    coverage_amount text,
    coverage_currency text,
    activation_trigger text,
    minimum_ticket_spend text,
    trip_duration_limit text,
    geographical_coverage text,
    deductible text,
    medical_cover text,
    baggage_cover text,
    flight_delay_cover text,
    cancellation_cover text,
    exclusions text,
    claim_process_url text,
    policy_document_url text,
    imported_at timestamptz default now()
);
create index wb_travel_insurance_card_idx on wb_travel_insurance (cardid);

-- Purchase Protection  (999 data rows)
drop table if exists wb_purchase_protection cascade;
create table wb_purchase_protection (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    purchase_protection_amount text,
    coverage_period_days text,
    eligible_purchase_type text,
    minimum_purchase_value text,
    deductible text,
    claim_window text,
    exclusions text,
    imported_at timestamptz default now()
);
create index wb_purchase_protection_card_idx on wb_purchase_protection (cardid);

-- Personal Accident  (999 data rows)
drop table if exists wb_personal_accident cascade;
create table wb_personal_accident (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    accident_cover_amount text,
    activation_condition text,
    travel_requirement text,
    coverage_duration text,
    beneficiary_rule text,
    exclusions text,
    imported_at timestamptz default now()
);
create index wb_personal_accident_card_idx on wb_personal_accident (cardid);

-- Roadside Assistance  (999 data rows)
drop table if exists wb_roadside_assistance cascade;
create table wb_roadside_assistance (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    service_provider text,
    free_service_count text,
    service_types text,
    geographical_limit text,
    response_time text,
    additional_service_fee text,
    imported_at timestamptz default now()
);
create index wb_roadside_assistance_card_idx on wb_roadside_assistance (cardid);

-- LTF (Lifetime Free)  (999 data rows)
drop table if exists wb_ltf_lifetime_free cascade;
create table wb_ltf_lifetime_free (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    notes text,
    imported_at timestamptz default now()
);
create index wb_ltf_lifetime_free_card_idx on wb_ltf_lifetime_free (cardid);

-- Status Benefits  (999 data rows)
drop table if exists wb_status_benefits cascade;
create table wb_status_benefits (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    status_program text,
    status_level text,
    qualification_method text,
    status_validity text,
    upgrade_benefit text,
    late_checkout text,
    breakfast text,
    eligible_properties text,
    imported_at timestamptz default now()
);
create index wb_status_benefits_card_idx on wb_status_benefits (cardid);

-- UPI  (999 data rows)
drop table if exists wb_upi cascade;
create table wb_upi (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    notes text,
    imported_at timestamptz default now()
);
create index wb_upi_card_idx on wb_upi (cardid);

-- Contactless  (999 data rows)
drop table if exists wb_contactless cascade;
create table wb_contactless (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    available text,
    network text,
    per_txn_limit text,
    notes text,
    source_id text,
    imported_at timestamptz default now()
);
create index wb_contactless_card_idx on wb_contactless (cardid);

-- Token Enabled  (999 data rows)
drop table if exists wb_token_enabled cascade;
create table wb_token_enabled (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    available text,
    supported_networks text,
    token_provider text,
    notes text,
    source_id text,
    imported_at timestamptz default now()
);
create index wb_token_enabled_card_idx on wb_token_enabled (cardid);

-- MCC  (999 data rows)
drop table if exists wb_mcc cascade;
create table wb_mcc (
    id uuid primary key default gen_random_uuid(),
    card text,
    offer_id text,
    mcc text,
    inclusion text,
    exclusion text,
    imported_at timestamptz default now()
);

-- Fees  (999 data rows)
drop table if exists wb_fees cascade;
create table wb_fees (
    id uuid primary key default gen_random_uuid(),
    cardid text,
    cardname text,
    issuer text,
    network text,
    subnetwork text,
    cardstatus text,
    feetype text,
    feeamount text,
    feeperiod text,
    applicabletaxes text,
    feewaivereligible text,
    feewaiverspend text,
    feewaiverperiod text,
    termsandconditions text,
    sourceofficial text,
    sourcesecondary text,
    startdate text,
    enddate text,
    cardstatusdate text,
    cobrand text,
    cobrandname text,
    status text,
    imported_at timestamptz default now()
);
create index wb_fees_card_idx on wb_fees (cardid);

do $$
declare t text;
begin
    foreach t in array array['wb_card_details', 'wb_offers', 'wb_lounge', 'wb_airport_transfer', 'wb_travel', 'wb_hotel', 'wb_airline', 'wb_forex_international', 'wb_reward_points', 'wb_milestone', 'wb_welcome', 'wb_renewal_benefit', 'wb_fee_waiver', 'wb_partner_and_transfer', 'wb_fuel', 'wb_dining', 'wb_golf', 'wb_movie', 'wb_spa_wellness', 'wb_concierge', 'wb_shopping', 'wb_ott_subscription', 'wb_insurance_protection', 'wb_travel_insurance', 'wb_purchase_protection', 'wb_personal_accident', 'wb_roadside_assistance', 'wb_ltf_lifetime_free', 'wb_status_benefits', 'wb_upi', 'wb_contactless', 'wb_token_enabled', 'wb_mcc', 'wb_fees']
    loop
        execute format('alter table %I enable row level security', t);
        execute format('drop policy if exists %I_anon_all on %I', t, t);
        execute format('create policy %I_anon_all on %I for all to anon, authenticated using (true) with check (true)', t, t);
    end loop;
end $$;
